### ISSUE TITLE
Add a page instructing users on how to get swag for their meetups and presentations about Crossplane

### ISSUE THREAD

**Issue by grantgumina** [crossplane/docs#113]
### What problem are you facing?
As Crossplane becomes increasingly popular, community members around the world are presenting about it at company brown bags, cloud-native meetups, and workshops they might do at conferences. It would be awesome if the Crossplane community were able to know about these events through an easy and intuitive self-reporting mechanism. That way the community could amplify these talks through social media and support the presenters with SWAG.

### How could Upbound help solve your problem?
There could be a page on crossplane.io linked to from the header which includes a form that community members can submit and make us aware of talks they're doing by adding them to a shared Google Calendar.

**Comment by plumbis** [comment]
@grantgumina do you still want this?

**Comment by grantgumina** [comment]
Ha forgot about this guy! Yes, I believe some community members would really benefit from an easy way to request support, promotion, and visibility of the evangelism work they're doing around Crossplane. From an Upbound side of things, we'd love to support and sponsor these efforts too - even if it were just retweeting someone's work. Whatever solution we build here, Upbound (and other vendors in the XP ecosystem) would love to have visibility into the requests being submitted.
