### ISSUE TITLE
Improve Search Results (include version)

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#202]
Algolia can solve this but it's more complicated than I originally thought. Today's search a basic implementation of [DocSearch](https://docsearch.algolia.com/). 

We need to build custom [Algolia widgets](https://www.algolia.com/doc/guides/building-search-ui/widgets/showcase/js/) to expand the functionality. 

The goals for this issue are: 
* Provide the ability to search only on a specific version or versions
* Return version numbers with the search results
* Add future support to filter on "knowledge base" or "docs" 

Nice to haves:
* Results and previews similar to how [Algolia docs results](https://www.algolia.com/doc/?q=test) are returned.
* Support for [Algolia metrics](https://unomena.atlassian.net/browse/UP-100#:~:text=Add%20Algolia-,click/convert,-metrics) to see what's being searched for and what is missing.

**Comment by plumbis** [comment]
We've applied to [Algolia DocSearch](https://docsearch.algolia.com/) and this should make this problem much easier to solve.

**Comment by jbw976** [comment]
@plumbis, another potential way to improve search is that perhaps right now the results are a bit too "fuzzy".  e.g. I type in "log" and the top 3 results (and many others further down) are for other words entirely, like "looking" and "local".  See screenshot below - is it possible to tune the "fuzziness" of the search results? (i don't know the proper terminology, sorry!)

![Screenshot 2023-02-07 at 11 45 16 AM](https://user-images.githubusercontent.com/4313439/217349633-88672bd2-41dd-4fb0-a6f9-b4d066221254.png)

**Comment by jbw976** [comment]
Another idea is to have the search box right there on the main landing page too: https://docs.crossplane.io/

sometimes I go there and I'm ready to search for a specific term, but I have to first click into one of the sub sections (which one do i click?), before I am presented with a search box.
