### ISSUE TITLE
dark mode not working

### ISSUE THREAD

**Issue by bassam** [crossplane/docs#216]
clicking on the dark mode button does not change anything for me

**Comment by plumbis** [comment]
Do you have JavaScript disabled? It's required for the toggle.

**Comment by plumbis** [comment]
Assuming you do, if you open the web inspector in web tools do you see any errors before or after you click the toggle?

**Comment by bassam** [comment]
I don't have javascript disabled - I dont see errors. I tried safari and chrome - same results.

**Comment by plumbis** [comment]
I'm not sure what else would cause the issue. The toggle fires a JS element adds `color-them="dark"` to the`<html>` tag-

```
<html lang="en" class="color-toggle-hidden" color-theme="dark">
```

If JS is working and it's cross browser something else is going on. My guess is it's some extension or plugin (but in both browsers? seems unlikely) changing behaviors. 

Would you have a few minutes to jump on a Zoom sometime to look at it together?

**Comment by plumbis** [comment]
I haven't heard other reports and I can't reproduce. I'll close this on Feb 10.
