### ISSUE TITLE
website and docs header should match

### ISSUE THREAD

**Issue by bassam** [crossplane/docs#217]
from the website:
<img width="1733" alt="CleanShot 2022-12-01 at 15 51 46@2x" src="https://user-images.githubusercontent.com/1463491/205183363-de5b2e34-681b-4258-b874-c5c310e05fff.png">

from the docs:
<img width="1728" alt="CleanShot 2022-12-01 at 15 51 01@2x" src="https://user-images.githubusercontent.com/1463491/205183336-fec14aa9-fa7e-4269-9140-76f8b306eeb1.png">

I think the two should be identical. I recommend moving the dark mode button below the header as a result.

**Comment by plumbis** [comment]
The spacing and logo contrast can/should be fixed.

For the dark-mode toggle this was a conscious choice to keep it outside of the body of the page and to make it play nice with mobile (the toggle goes into the same menu as the rest of the top links if you collapse the page down).

Moving the toggle is possible but I think it will it will be a less desirable UX.

**Comment by plumbis** [comment]
The logo and center links now match. I'm closing this as completed. Feel free to reopen or open another issue to discuss the slack, github and darkmode buttons.
