### ISSUE TITLE
the table of contents should be pinned until the content ends

### ISSUE THREAD

**Issue by bassam** [crossplane/docs#218]
the table of contents on the left should not scroll with the content. the behavior should more like the following:

![CleanShot 2022-12-01 at 15 58 41](https://user-images.githubusercontent.com/1463491/205184185-21669d0d-dbc8-4048-979e-04dc8a2fb612.gif)

**Comment by plumbis** [comment]
Where did you see this behavior? The right nav _should_ be sticky. Here is a recording from me scrolling through the docs contributing page.


![Screen Recording 2022-12-01 at 7 49 07 PM 2022-12-01 19_52_34](https://user-images.githubusercontent.com/10537576/205190158-9161bf02-919e-4987-8276-8918d5596dba.gif)

**Comment by bassam** [comment]
its the table of contents on the LEFT - not right

**Comment by plumbis** [comment]
🤦
