### ISSUE TITLE
Feedback from community member

### ISSUE THREAD

**Issue by luebken** [crossplane/docs#219]
Some feedback from a handsome community member in German thread in Linkedin:

What could be improved in the docs:

* Overview of the Crossplane CRDs and how they are opinionated.
* What is CompositionRef, ToCompositeFieldPath, FromCompositeFieldPath. Overview. Explanation
* Relation of Claims, XRD, Compositions + XRs. Is documented. Still not clear.
* What happens if there is no defaultCompositionRef and there are multiple Compositions.
* For every opinionated Crossplane extension, there should be a section with explanation and diagram. 

* How to Monitoring

via @erkules

**Comment by erkules** [comment]
I would think about redesigning also the XR-Compostion page.
It is highly irritating when you want to Check Compositions and the side starts with  https://docs.crossplane.io/v1.10/concepts/composition/
Please make it clear i.e.:
As an Infra I create Compostions and XRDs and the Consumer creates the Claim/XR. 
Maybe using Kubernetes analogies would be fine aka:
While we still have our opinionated way [link2diff2NormaloCRDs] to use CRDs. 
Think about Compositions as a declarative way to configure/create specific Controllers and XRDs are just opiniated CustomResourceDefinition but basically creating the CRD for the Consumer to use. Wenn you create an Object we all it XR/Claim but in the end it is an Object an a "ConsumerController" picks the Claim and creates/configures it.

An approach like this would use patterns we know already and Compostions wouldn't be a Miracle Ressouce anymore (scnr).

thx4Crossplane kinda interesting <3

**Comment by plumbis** [comment]
Some of these points are (hopefully) addressed with the v1.11 docs update. 

> Overview of the Crossplane CRDs and how they are opinionated.
> ... 
> Relation of Claims, XRD, Compositions + XRs. Is documented. Still not clear.

A [new intro page](https://docs.crossplane.io/v1.11/getting-started/introduction/) introduces XRDs and CRDs and puts them into context. A [new AWS quickstart](https://docs.crossplane.io/v1.11/getting-started/provider-aws/) page also tries to explain this in simple terms.

**Comment by plumbis** [comment]
Fixed in #475
