### ISSUE TITLE
Add "contribute to this page" hints

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/docs#234]
As a community user,
in order to contribute to docs
I need to discover the github file associated to a doc page

Example:
https://docs.cloudfoundry.org/
![image](https://user-images.githubusercontent.com/4748380/207892570-696998f0-be52-4bab-9117-e1a3b8b908d6.png)

**Comment by plumbis** [comment]
Good feedback. We'll add a github link for the docs. You may also want to take a look at our [Docs contributing guide](https://docs.crossplane.io/master/contributing/docs/).

**Comment by gberche-orange** [comment]
thanks @plumbis,  the docs contributing guide is awesome!

**Comment by plumbis** [comment]
This will be added when PR #254 is incorporated.

**Comment by plumbis** [comment]
This is now live. Closing as completed.
