### ISSUE TITLE
Confusion: What is a "Control Plane"?

### ISSUE THREAD

**Issue by Gowiem** [crossplane/docs#273]
### What problem are you facing?

Hey folks, small thing, I'm by no means a newcomer to the IaC, Kubernetes, or cloud native ecosystem and yet I always struggle with your practice of calling Crossplane a "Control Plane". This doesn't mean anything to me and I haven't seen a definition of that term on either the crossplane.io site or in the documentation. I think it would help me and others if you defined what that is in both of those locations, because it seems taken for granted that the term is largely understood, but I don't think that is the case. To support wider adoption and less confusion for newcomers to XP, defining that terms seems like an important checkbox.

Also, I think it's worth noting, if you google "What is a control plane?", you end up with a bunch of networking related terminology which is not what you folks are getting at AFAIU:

![CleanShot 2022-12-14 at 10 43 26](https://user-images.githubusercontent.com/1392040/207668596-1a2a08e9-a764-4a71-a9f9-9ffa1f03c472.png)

### How could Crossplane help solve your problem?

Provide me a great definition here and I'd be happy to do a documentation update for [the terminology page](https://docs.crossplane.io/v1.10/concepts/terminology/).

**Comment by plumbis** [comment]
I wrote a new "Intro" section that will be published tomorrow that tries to describe what a control plane is and how Crossplane fits into the model. 

https://deploy-preview-271--crossplane.netlify.app/v1.11/

**Comment by plumbis** [comment]
This is now live

https://docs.crossplane.io/v1.11/

I'll close this out but feel free to reopen if you feel it's still confusing.
