### ISSUE TITLE
Document manual population of package cache

### ISSUE THREAD

**Issue by hasheddan** [crossplane/docs#277]
### What problem are you facing?

Populating Crossplane's package cache manually can be useful to avoid having to push package images to a registry during development. One place we do this today is in CI for providers. However, there is not currently good documentation on how to do it.

### How could Crossplane help solve your problem?

Add documentation for manually populating package cache.

**Comment by plumbis** [comment]
Discussed in the provider chapter

https://docs.crossplane.io/latest/concepts/providers/#install-offline
