### ISSUE TITLE
Proposal: Rev the Getting Started Guide on XP Docs

### ISSUE THREAD

**Issue by cwilhit** [crossplane/docs#279]
### What problem are you facing?

I've been talking with a lot of users in the community and I've noticed a theme that the docs--`getting started`, notably--are difficult to follow. The guide introduces a lot of technical concepts at once (with plenty of acronyms, to boot). Make no mistake: the Crossplane documentation is packed with a lot of great content. But it needs to reworked to lower the learning curve.

### How could Crossplane help solve your problem?

I propose we start by reworking the Getting Started guide -- reducing the number of concepts we expose immediately to readers, reduce the usage of acronyms, and simplify the install journey to document the happy path (for example: why are users shown a toggle between Helm 3 XP stable and Helm 3 XP latest? The guide should steer users towards the simple path and push this sort of 'advanced' content into a separate topic doc).

Over time, we should look at closing other 'guide' gaps, but let's start with the one that users hit the most out the gate: `getting started`

**Comment by plumbis** [comment]
@cwilhit a brand new quickstart was written for AWS (expansions to Azure and GCP soon). Please take a look.
https://docs.crossplane.io/v1.11/getting-started/provider-aws/

I'll close this one out, but feel free to reopen if you have comments or concerns.
