### ISSUE TITLE
Documentation issue: An architecture diagram depicting the network dependencies of Crossplane is missing.

### ISSUE THREAD

**Issue by NearchPasipou** [crossplane/docs#286]
Setting up Network Policies for applications deployed on (for example: EKS) kubernetes clusters is a typical security requirement.
Instead of attempting to reverse engineer the Egress and Ingress paths that Crossplane might need to function, a guideline must be provided in some part of Crossplane documentation.

**Comment by plumbis** [comment]
@NearchPasipou can you give me some more details on what you're looking for? Are you looking for a flow diagram of which pod speaks to which and who needs external internet access? 

Would you be able to give me a rough example of what you have in mind?

**Comment by plumbis** [comment]
Closing as inactive.
