### ISSUE TITLE
Restart XR and claim controllers when XRDs are updated

### ISSUE THREAD

**Issue by muvaf** [crossplane/docs#288]
### What problem are you facing?

I might be the only one who knows about this since I did the initial implementation so we need to document it. The reason is that we spin up a new controller for every CRD we produce but those controllers work on the cached schema, so the schema cache needs to be refreshed and that doesn't happen unless you restart the pod (the last I checked).

### How could Crossplane help solve your problem?

Add this to composition reference doc.

**Comment by plumbis** [comment]
Fixed in #475
