### ISSUE TITLE
Release Crossplane version v1.11.0

### ISSUE THREAD

**Issue by phisco** [crossplane/docs#304]
- [ ] Update the `/latest` redirect in [netlify.toml](https://github.com/crossplane/docs/blob/master/netlify.toml#L9)
- [ ] Update `params.latest` in [config.yaml](https://github.com/crossplane/docs/blob/master/config.yaml#L48)

**Comment by plumbis** [comment]
`config.yaml` updated- https://github.com/crossplane/docs/pull/271/files#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489ed

`netlify.toml` updated - https://github.com/crossplane/docs/pull/271/files#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489ed

**Comment by plumbis** [comment]
#271 merged to master and live.
