### ISSUE TITLE
User guide for EnvironmentConfig

### ISSUE THREAD

**Issue by jbw976** [crossplane/docs#305]
The ability to use configuration values from the environment is a great new feature in v1.11: https://github.com/crossplane/crossplane/issues/2099.

We have some guidance on how to use them from a composition patching perspective, e.g. `*Environment*` in https://docs.crossplane.io/master/reference/composition/#patch-types, but it would also be helpful to have a complete end to end user guide for how to create and use EnvironmentConfig.

There was a small yaml only (no written prose or context) end to end example in the old docs snippets (see links below), but those are being cleaned up and removed.  We could use those as a starting point to author a complete end to end guide on how to use EnvironmentConfig.

* Discussion and context for this issue: [discussion link](https://github.com/crossplane/docs/pull/271#discussion_r1085960840)
* Commit with example YAML: https://github.com/crossplane/docs/commit/4c35456406dd282f0688d83f063ad55b8630f1f2#diff-d9549ed3cf00d1a20eb5fc1c51194ead6078f9e48cc62c62c8e3284c3306b72f

**Comment by djeremiah** [comment]
Existing patch docs have moved to https://docs.crossplane.io/master/concepts/composition/#patch-types
