### ISSUE TITLE
Inconsistent abbreviations for Composite Resource Claim

### ISSUE THREAD

**Issue by negz** [crossplane/docs#313]
### URL

https://github.com/crossplane/docs/blob/542668/content/v1.11/getting-started/introduction.md?plain=1#L46
https://github.com/crossplane/docs/blob/542668/content/v1.11/getting-started/provider-aws.md?plain=1#L14

Possibly more - I haven't checked all of https://github.com/search?q=repo%3Acrossplane%2Fdocs+XC&type=code

### What's Wrong?

The documentation has a few places that abbreviate claims to "XC". Historically we've abbreviated them to "XRC" for "Composite Resource Claim", per:

* https://github.com/search?q=repo%3Acrossplane%2Fcrossplane+XRC&type=code
* https://github.com/crossplane/docs/blob/master/content/v1.11/concepts/terminology.md#composite-resource-claim

My priority is to be consistent. That said, I'd prefer to standardize on XRC.

**Comment by negz** [comment]
I'm happy to open a PR for this, just checking that we're aligned before I do.

**Comment by plumbis** [comment]
Fine with me, I have no opinions here. I don't remember where I found the `XC` reference but I missed `XRC` originally. Thanks for catching and fixing it.
