### ISSUE TITLE
Confirm Algolia crawler is working properly

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#315]
### What's Wrong?
[Composite Functions](https://docs.crossplane.io/knowledge-base/guides/composition-functions/) aren't appearing in search outputs.

A quick look at our Algolia crawler implies that the KB isn't being picked up by Algolia. 
![Screenshot 2023-02-01 at 3 17 34 PM](https://user-images.githubusercontent.com/10537576/216154016-3b592e33-b3c5-4292-88a8-2cc78d5b7b54.png)

This needs to be double checked to see what's up. Either it's not being crawled or the index isn't being updated properly.

**Comment by plumbis** [comment]
This is problem is a combination of things: 
1. More metadata is needed in the pages to help sorting. #324 does this
2. The prioritization of Algolia results needed to be changed. This was done on the algolia dashboard.

<img width="610" alt="Screenshot 2023-02-01 at 9 01 53 PM" src="https://user-images.githubusercontent.com/10537576/216212959-c76b7495-991b-412d-b542-adbfea08ed0b.png">

**Comment by jbw976** [comment]
nice nice nice @plumbis!! i can now find "composition functions" in the search results - big improvement!! 💪
