### ISSUE TITLE
Move Composition Revision and Composition Function guides to v1.11?

### ISSUE THREAD

**Issue by negz** [crossplane/docs#316]
### What's Missing?

My understanding of the Knowledge Base section of the docs is that it should contain topics that aren't strongly coupled to a particular version of Crossplane. What is and isn't coupled is probably a little ambiguous, but I was surprised to find the Comp Revisions and Comp Functions documentation in the knowledge base.

I would imagine this documentation would change with a new version, and that it would be useful to keep the old version of the docs around. For example Composition Revisions may become v1/GA in Crossplane v1.12, but I would still want a reader who was running Crossplane v1.11 (and thus presumably browsing the Crossplane v1.11 docs) to see the "This is a beta feature" warning, v1beta1 API schema, etc.

**Comment by negz** [comment]
FWIW @ldalorion ran through using a Composition Function today in a little UX test we ran with a few Upbound engineers, and her intuition was to look where the guides already are.

**Comment by plumbis** [comment]
XfNs moved to the docs for v1.13.
