### ISSUE TITLE
Can we avoid here documents?

### ISSUE THREAD

**Issue by negz** [crossplane/docs#321]
### URL

https://github.com/search?q=repo%3Acrossplane%2Fdocs%20EOF&type=code

### What's Wrong?

We've recently added several code examples that use shell here documents (i.e. `cat <<EOF`) to create paste-able `kubectl` commands. I feel this is a UX regression compared to our previous practice of offering a code block that shows only the content of a manifest, and a separate kubectl command that applies that manifest. You can see examples of that pattern in the Kubernetes documentation - for example https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-to-create-objects.

My concern with here documents are:

* They're an intermediate level shell scripting technique that may not be intuitive/self-documenting to all readers.
* They're not supported by all shells ([e.g. fish](https://fishshell.com/docs/current/fish_for_bash_users.html#heredocs)).
* It's (arguably) tough to visually distinguish at a glance what is data and what is a command

<img width="912" alt="Screenshot 2023-02-01 at 1 37 12 PM" src="https://user-images.githubusercontent.com/1049349/216168950-5466b203-6494-4941-a082-8264efe7af11.png">

**Comment by negz** [comment]
I'm not necessarily advocating to return to the old pattern - my priority is to find an alternative to here documents.

The biggest issue we had with the old pattern was that we needed to keep two copies of every example updated, and thus they frequently became out of sync. I notice that the Kubernetes docs appear to have a special shortcode that "includes" a code example from a separate file - for example https://github.com/kubernetes/website/blob/8a320d4dd2c76931e0221e4e26385366ea71df2a/content/en/docs/tasks/manage-kubernetes-objects/declarative-config.md#L78.

This approach appeals to me because:

* It allows a single file to be rendered inline, and used as the argument to an example `kubectl apply` command.
* Example code snippets exist as distinct files that could be (e.g.) linted using their native tooling.
* It "abbreviates" the code blocks when editing markdown.

**Comment by plumbis** [comment]
What is the "old pattern"?

**Comment by negz** [comment]
> You can see examples of that pattern in the Kubernetes documentation - for example https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-to-create-objects.

^ This is what I'm referring to as "the old pattern". It's what we used to do for all our YAML manifest examples. We copied it from what the Kubernetes docs does (only we didn't have the benefit of their handy shortcode).

**Comment by plumbis** [comment]
Gotcha.

My gut reaction is to support this. I think there's a lot of value with keeping the output files outside of the docs has a lot of downstream benefits, as you said `kubectl apply -f <url>` and linting/testing. 

I want to think a little bit about the workflow aspect. Seeing the code inline makes describing what you're talking about  while writing easier and the `{{<hover >}}` shortcode depends on line numbers. Seeing it next to the example makes it easier, but I doubt this is a blocker.

**Comment by negz** [comment]
> Seeing the code inline makes describing what you're talking about while writing easier and the {{<hover >}} shortcode depends on line numbers. Seeing it next to the example makes it easier, but I doubt this is a blocker.

FWIW my personal experience editing docs is mixed on this. I could imagine it being a PITA to have to go look at some separate file, but at the same time it's also often a PITA to have to scroll through some of our more gigantic walls of config (i.e. the type that are hidden in an expand block in the rendered docs, but not in the markdown).

**Comment by plumbis** [comment]
It's been awhile since these docs went live and there hasn't been additional feedback about heredocs being a problem. I'm goign to close this one out.
