### ISSUE TITLE
Link to Composition Revisions, Functions, etc from "main" Composition docs

### ISSUE THREAD

**Issue by negz** [crossplane/docs#323]
### What's Missing?

I want to keep non-GA Composition features like Revisions and Functions "contained" - separate from the documentation of GA features. I believe this removes any ambiguity around what features are GA and what features folks should be more conscious of opting into. This makes discoverability tricky though, per the below feedback:

<img width="979" alt="Screenshot 2023-02-01 at 4 36 46 PM" src="https://user-images.githubusercontent.com/1049349/216201931-364e8b47-1d2c-4d65-9d90-f28555762a29.png">

One compromise that comes immediately to mind would be to cross-link. Have the Composition docs link to the pages of any alpha or beta features, and have those features link back to the broader Composition docs.

**Comment by plumbis** [comment]
I would argue that the KB is currently the wrong home for the Composite Functions page, since it is specific to v1.11. As future are release the capabilities and rules of of CompFn are likely to evolve making the doc version-dependent. 

Since it's a new `kind` I would say this should live under `/concepts`.

**Comment by negz** [comment]
> I would argue that the KB is currently the wrong home for the Composite Functions page, since it is specific to v1.11.

Agreed - I raised https://github.com/crossplane/docs/issues/316 yesterday to discuss that.

> Since it's a new `kind` I would say this should live under /concepts.

It's actually not a new `kind` (or more specifically it introduces no new CRD - `FunctionIO` is kind of special). Instead it's an extension of the `kind: Composition` type. This makes finding a home a bit tricky. If the feature were GA today I would say it should be part of the Composition documentation. The only reason I want to keep it separate for now is because it's pre-GA and I want to make it as easy as possible for readers to delineate GA stuff from not-yet-GA stuff.

**Comment by plumbis** [comment]
Fixed in #475
