### ISSUE TITLE
Some pages conflate CRDs with CRs

### ISSUE THREAD

**Issue by negz** [crossplane/docs#325]
### URL

At least https://docs.crossplane.io/v1.11/getting-started/introduction/, possibly others.

### What's Wrong?

Our latest documentation conflates Kubernetes Custom Resources (CRs) with Custom Resource Definitions (CRDs). Anecdotally I think this is quite common in the Kubernetes ecosystem, but I would prefer our documentation to use correct terminology.

* https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#custom-resources 
* https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions 

For example:

> Within the bucket CRD is a [spec.forProvider.region](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.25.0/resources/s3.aws.upbound.io/Bucket/v1beta1#doc:spec-forProvider-region) value that defines which AWS region to deploy the bucket in.

I believe this is talking about an API resource (or YAML manifest) of `kind: Bucket`. This is a CR. The CR as a type exists because it is "defined into existence" by a CRD - like the difference between a type definition and an instance of a type in a programming language.

> For example, an AWS Provider defines Kubernetes CRDs for AWS resources like EC2 compute instances or S3 storage buckets.

This is not strictly incorrect, but I think it would make more sense to say that a provider either "installs CRDs" or "defines CRs". "Defines Custom Resource Definitions" stutters.

**Comment by plumbis** [comment]
This is getting addressed in #326 right?

**Comment by negz** [comment]
No, or at least I definitely didn't catch all of them. That PR is already pretty sprawling so I'd prefer to tackle this separately. I think we probably need at least a hint/tip explaining what a CR is before we start making the distinction.

**Comment by plumbis** [comment]
This is resolved with #427
