### ISSUE TITLE
"Building a configuration package" inaccuracies

### ISSUE THREAD

**Issue by negz** [crossplane/docs#331]
### URL

https://docs.crossplane.io/v1.11/getting-started/provider-aws-part-3/#build-a-configuration-package

### What's Wrong?

<img width="1023" alt="Screenshot 2023-02-02 at 6 46 38 PM" src="https://user-images.githubusercontent.com/1049349/216500461-9a334f96-eac9-4d0c-9ca0-eae214436f50.png">

There's two inaccuracies in the above screenshot:

* I'm pretty sure we mean the [`up`](https://github.com/upbound/up) CLI can be used to build images, not UXP.
* Most config packages contain those three files, but I think the only hard requirement is that they have a `crossplane.yaml` and at least one XRD or Composition.

You could have a config package with 20 XRDs and no Compositions, or vice versa, and I believe the package parser will find them regardless of their filenames, whether they're in a nested directory etc. There's actually a specification that describes all of this but I think it was accidentally deleted when the docs got moved. @hasheddan is working on resurrecting it.

**Comment by negz** [comment]
Piling on with another thing I'd like to improve on that page (sorry, about to leave the house so no time for a separate issue) is that it's a best practice to always include the `type` of a patch. Given patches can actually be `ToCompositeFieldPath` or `FromCompositeFieldPath` I feel that including the type makes them more self-documenting and a practice we should model for Crossplane users.

**Comment by plumbis** [comment]
> I'm pretty sure we mean the [up](https://github.com/upbound/up) CLI can be used to build images, not UXP.

You are correct, thank you.

> Most config packages contain those three files, but I think the only hard requirement...

Understood, in this case since it's a quick start and not the "packages" guide I'm willing to be a little loose with the rules to say "hey, want a package? do these things to get started". As the reader learns more we can expose additional options and flexibility to the original instructions.  Introducing optionality introduces complexity and in this specific context the goal is to just introduce the concept of a package. It's the same reason provider packages aren't introduced as an option, it's just more complexity.

>  it's a best practice to always include the type of a patch.

Sorry, I don't know what this is referencing. The [example Composition patch](https://docs.crossplane.io/v1.11/getting-started/provider-aws-part-3/#hl-11-46) includes a `map` type

**Comment by negz** [comment]
> Sorry, I don't know what this is referencing.

```yaml
patches:
- type: FromCompositeFieldPath  # This is the type I was talking about
  fromFieldPath: "spec.region"
  toFieldPath: "spec.forProvider.region"
  transforms:
  - type: map
    map: 
      EU: "eu-north-1"
      US: "us-east-1"
```

This particular `type` field is optional and defaults to `FromCompositeFieldPath`. I regret the fact that it's optional though - if I had an API design do-over it would be required. It makes what the composition is doing less ambiguous. I think it's a good practice to always include it in examples because folks will cargo-cult the conventions that they see.

**Comment by negz** [comment]
> Understood, in this case since it's a quick start and not the "packages" guide I'm willing to be a little loose with the rules to say "hey, want a package? do these things to get started".

I completely agree with the sentiment here. I don't think we need to explain what can be in a Configuration package at this point, but I would prefer to rephrase "A Configuration package includes three files". It reads to me as if it's stating that all Configuration files include three files. If someone never read on to the more detailed guide they could operate under the assumption that was a constraint for some time. Would "This Configuration package includes three files" or similar make sense?
