### ISSUE TITLE
Broken link and no 1.11 snippets?

### ISSUE THREAD

**Issue by bobh66** [crossplane/docs#333]
### URL
https://docs.crossplane.io/v1.11/concepts/packages/#configuration-packages

### What's Wrong?
The link to the GCP packages example is broken - https://github.com/crossplane/crossplane/tree/master/docs/snippets/package/gcp

Also there is no snippets content under 1.11 as there is under 1.10 and 1.9

**Comment by negz** [comment]
Cross-referencing https://github.com/crossplane/crossplane/pull/3713. We had moved these configurations and I was about to delete them.

**Comment by plumbis** [comment]
This will be fixed with #344
