### ISSUE TITLE
[Web Bug] - Providers - Getting Started Link does not work

### ISSUE THREAD

**Issue by philippart** [crossplane/docs#334]
The link "Getting Started" (https://docs.crossplane.io/v1.11/concepts/providers/%22../getting-started/install-configure%22) doesnt work (page not found).

URL: /v1.11/concepts/providers/

**Comment by jbw976** [comment]
Thanks for reporting this @philippart! Does this link work OK for you? https://docs.crossplane.io/v1.11/concepts/providers/

Can you share where you are seeing/finding the link that you opened this issue about? 🕵️

**Comment by plumbis** [comment]
This is fixed with #344
