### ISSUE TITLE
Instructions on how to compile a Crossplane Provider with just a subset of the available CRDs

### ISSUE THREAD

**Issue by nicolas-g** [crossplane/docs#336]
### What's Missing?
As we all know, the number of CRDs significantly impacts the Kubernetes cluster performance.

For deployments that only require a small number of CRDs, it will be good to have instructions on compiling the Crossplnae provider with just a tiny number or CRDs.

**Comment by jbw976** [comment]
Related to https://github.com/crossplane/crossplane/issues/2869

**Comment by negz** [comment]
I don't think we should document how to do this. It's not a practice we support.

As soon as we have bandwidth on the maintainer team we'll be starting work on a design document to address https://github.com/crossplane/crossplane/issues/2869.

**Comment by jbw976** [comment]
Here's some related discussion for further context @nicolas-g: https://github.com/crossplane/crossplane/issues/2895#issuecomment-1379781246

**Comment by plumbis** [comment]
I'm going to close this as "won't fix" and out of scope for the user docs. The Provider section update in #420 now has a mention and link to the contrib guide on building your own providers.
