### ISSUE TITLE
Enable link checking

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#340]
### What's Wrong?
There is no automated checking for broken links. This should be enabled as part of any PR.

**Comment by plumbis** [comment]
https://github.com/wjdp/htmltest seems to be a great tool recommended by other doc platforms using static site generators. 

Running against the v1.11 docs, ignoring external links, takes just under 200ms
```
bin/htmltest -c utils/htmltest/.htmltest.yml
htmltest started at 01:51:43 on public
========================================================================
✔✔✔ passed in 168.751ms
tested 141 documents
```

Checking for external links takes 8 minutes. 
```
htmltest started at 01:53:07 on public
========================================================================
# Errors removed for brevity
========================================================================
✘✘✘ failed in 8m22.039551625s
18 errors in 141 documents
```

We **shouldn't** enable this for PRs but consider a weekly github job or something. This should be evaluated outside the scope of this issue.

**Comment by paulfantom** [comment]
> We shouldn't enable this for PRs but consider a weekly github job or something. This should be evaluated outside the scope of this issue.

My 5 cents as someone who was implementing such checkers in other repositories. If this is not putting too much strain on CI, consider still running it on every PR but just make sure it is not blocking merges. Usually, this approach leads to much better outcomes as you can catch issues early while still ignoring false positives.

---

In #332 I was suggesting to use `mdox` as an alternative tool for link checking. The nice thing about that tool as opposed to [wjdp/htmltest](https://github.com/wjdp/htmltest) is that it can do validation on plain markdown files so there is no need to pre-generate site and thus it may be easier to implement in CI.

If you decide to go with `mdox` I can offer my help with setting up CI for it :)

**Comment by plumbis** [comment]
@paulfantom thanks for the feedback!

There's definitely value in having mdox run against the markdown without running `hugo` to build the site, but for us there are additional checks that Hugo provides for us, including ensuring alt text is applied to shortcode images and that the `ref` shortcode for intra-site links are valid.   If we run `mdox` for checking we'll still need to run `hugo` and build the site.
