### ISSUE TITLE
Align clipboard icon with top line when {copy-lines="1"}

### ISSUE THREAD

**Issue by jbw976** [crossplane/docs#346]
From the discussion in https://github.com/crossplane/docs/pull/337#discussion_r1096567786, it could be a nice user experience improvement to vertically align the copy to clipboard icon with the top line of a code block, when only the first line will be copied, i.e. when `{copy-lines="1"}`.

@plumbis also added in https://github.com/crossplane/docs/pull/337#issuecomment-1416814888:
> I'll take a look at mapping the copy icon with a visual indicator of the lines that will be copied.

**Comment by plumbis** [comment]
Trying to get the spacing right on this one was wonky so I have an alternative proposal: highlight the lines to be copied when you hover over the clipboard.

(ignore the fact the clipboard moved here, just part of testing)

**Single Line**
![Screenshot 2023-02-10 at 11 17 25 AM](https://user-images.githubusercontent.com/10537576/218141790-bff84fcb-fb5a-4f78-90f6-47cef6a35cd9.png)

**All lines**
![Screenshot 2023-02-10 at 11 17 28 AM](https://user-images.githubusercontent.com/10537576/218141922-354d30e6-89fa-4784-9184-98d5dcb08743.png)

**Subset of lines**
![Screenshot 2023-02-10 at 11 19 17 AM](https://user-images.githubusercontent.com/10537576/218142050-cc665220-81c3-43ae-b657-f30f9c38f452.png)

**Comment by jbw976** [comment]
that seems pretty reasonable and clear @plumbis! it should make it obvious what is going to be copied.

you said to ignore the clipboard location movement, but....do you think it's better on the left side? or you will keep it on the right side? :)
