### ISSUE TITLE
Links do not render within hint shortcode blocks

### ISSUE THREAD

**Issue by hasheddan** [crossplane/docs#350]
### What's Wrong?

I noticed when adding a `warning` block in #349 that I was unable to add a link and have it render properly within the `hint` block.

**Comment by plumbis** [comment]
It seems like this is only an issue with [reference style](https://gist.github.com/emedinaa/28ed71b450243aba48accd634679f805#file-markdown-reference-links-L5) links, is that right?

This code:
```markdown
{{<hint "warning" >}}
Some text!  
[order a pizza](https://blog.crossplane.io/providers-101-ordering-pizza-with-kubernetes-and-crossplane/) 

[`ControllerConfig` API][controller-config-docs]

[Install software]({{< ref "software/install" >}})
{{< /hint >}}
```

Rendered this output
<img width="508" alt="Screenshot 2023-02-09 at 3 14 15 PM" src="https://user-images.githubusercontent.com/10537576/217926761-d47cd67d-7af1-419b-a0f6-970c89bd2f99.png">

The style guide reference [implies that markdown inline link styles](https://docs.crossplane.io/contribute/features/#links) should be used. 

I can make this more explicit if you'd like.
