### ISSUE TITLE
[Web Bug] - Lots of broken links in the documentation

### ISSUE THREAD

**Issue by mocdaniel** [crossplane/docs#353]
Many links in the documentation are broken, seemingly only the ones which cross-link to other parts of the docs. They seem to be formatted `[description][destination]` instead of `[description](destination)`. 

I could go through the docs again and try to fix all broken links, if that is appreciated, feel free to assign me to this issue, and I'll open a PR over the next days.

URL: /v1.11/concepts/composition/

**Comment by plumbis** [comment]
Thanks @mocdaniel !

These broken links along with CI to prevent it in the future are addressed in https://github.com/crossplane/docs/pull/344

Should be fixed soon.

**Comment by plumbis** [comment]
#344 was just merged, if you find anything else please let us know!
