### ISSUE TITLE
Add prettier job for code formatting consistency

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/docs#365]
To ensure consistency in the formatting of our code, it will be advantageous to use something like [prettier/prettier](https://github.com/prettier/prettier) on PRs to ensure consistent formatting.

We can also consider adding it as a pre-commit hook so that it's picked up before committing the code while developing locally.

**Comment by jeanduplessis** [comment]
@plumbis thoughts on this?

**Comment by plumbis** [comment]
I support it and it'd make me feel better about https://github.com/crossplane/docs/issues/321 as well.

**Comment by plumbis** [comment]
I spent a little time poking at this but couldn't get the regex right. 

The only code we have that Prettier could act on is YAML, and there's definitely value in making sure we get it right, but to do this we'd have to have a script parse the page changed in the PR (just like Vale does) and then extract the code blocks.

I used [this repo](https://github.com/shamrin/codeblocks) as a starting point but their regex won't capture blocks with attribute labels (i.e., ` ```yaml {label="blah"} ` ) 

I hacked on the regex and couldn't get it to match on a code fence with or without a label.

If someone wants to try and get a regex to extract the code blocks we could look more into folding in prettier.

I'm going to close as "won't do". If someone comes along and wants to give it a shot we can reopen.
