### ISSUE TITLE
[Discussion] Drop master docs version

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#366]
Today we publish docs for the Crossplane "master" branch. Part of this is an artifact from how docs were generated from the crossplane/crossplane repo.

Now that docs are independent from the c/c repo we should consider if we still need docs for the "master" release.

**Pros**
* Provides a 1:1 map of c/c branches to docs versions
* A building area for new content

**Cons**
* We don't have a workflow that puts new features into master docs. The new version is created and new content is put in there.
* Master is a duplicate of `latest`. There's no unique It's another place to change. Errors and content enhancements are copied to both versions.

**Comment by jeanduplessis** [comment]
@plumbis I'm wondering if this is an opportunity to re-evaluate how we publish different versions of the documentation.
My previous experience publishing different documentation versions used the branching strategy, where there was a branch for each version that would then get published to a /<version>/ namespace on the docs site.

Master was also published as /latest/.

**Comment by jeanduplessis** [comment]
What is our rationale currently for keeping the versions as folders in the repo?

**Comment by plumbis** [comment]
This was a conscious move away from the c/c repo method that followed this approach. The main motivation is that errors tend to propagate across versions. Fixing a typo in one version results in checking out and patching multiple branches and it's much more difficult to compare across versions instead of just ctrl + f in an IDE. 

The other motivation is working with more traditional technical writers it's a more complex git workflow which is much more likely to cause problems for them. It's not a problem we have today but something I wanted to eliminate as a barrier to entry for any contributors. I don't want there to be implicit knowledge of branches to versions when someone is trying to fix a problem for us.

A note on publishing as `/latest` we have that today but the URL redirect is enforced at the Netlify hosting level.

**Comment by plumbis** [comment]
there has been no additional comments on this. I'll bring this up again at the next community meeting on March 9.

Pending objections, the master branch will be dropped on Friday March 10.

**Comment by plumbis** [comment]
Great scenario to consider-

It would follow the existing "new version" workflow. Copy v1.11 and rename to v1.12. Add content to v1.12. Set the folder as a `draft: True` so it's not published before the release. 

Open to other suggestions/idea.

**Comment by jeanduplessis** [comment]
As long as we have a solution like you described that's easily accessible for contributors, then I think I'm okay with this.

**Comment by plumbis** [comment]
I'll be sure to capture this in the contrib guide when the change is made.
