### ISSUE TITLE
As Documents move with the refactor link to new location from old

### ISSUE THREAD

**Issue by jpoley** [crossplane/docs#377]
### What's Missing?

It would make it easier and a better user expereince as the docmentation gets refactored, to link to the new / changing / current location from the older verision (1.10 -> 1.11) 
one example is the argo-crossplane pages

**Comment by plumbis** [comment]
@jpoley I just submitted a PR for this that adds a header to all the pages. Take a look if you have a few minutes.

https://github.com/crossplane/docs/pull/378
