### ISSUE TITLE
Crossplane CLI install confusion

### ISSUE THREAD

**Issue by jbw976** [crossplane/docs#385]
### URL
* https://docs.crossplane.io/knowledge-base/guides/troubleshoot/#requested-resource-not-found
* https://docs.crossplane.io/v1.11/concepts/packages/
* https://docs.crossplane.io/v1.11/concepts/providers/

### What's Wrong?

In the Troubleshooting guide, we have an entry that mentions installing the Crossplane CLI and has what looks to be a broken markdown link syntax:

```
You can follow the [install Crossplane CLI] instructions to upgrade the plugin.
```

Furthermore, we suggest using `kubectl crossplane` in a few sections such as the Packages and Providers concepts pages linked above.  It appears we give users the `kubectl crossplane` commands to run, but never tell them how to actually get the Crossplane CLI plug-in installed. These commands would fail without having installed the plug-in.

A confounding factor here is that the Crossplane CLI could be deprecated in the future, a la https://github.com/crossplane/crossplane/issues/3055.  So most likely, we don't want to keep encouraging folks to install it.

It can be argued that the `up` CLI can replace all of the extant Crossplane CLI functionality, and has picked up broad usage across the ecosystem, for example as the build/push tool in many provider repos. However, any introduction of `up` to the docs should be in the context of it being just one example of any container image building tool that can be used to build Crossplane packages.

**Comment by plumbis** [comment]
Closing to build new CLI docs with the upcoming crossplane CLI work.
