### ISSUE TITLE
Out of sync helm chart values doc

### ISSUE THREAD

**Issue by phisco** [crossplane/docs#401]
### URL

https://docs.crossplane.io/master/software/install/#customize-the-crossplane-helm-chart

### What's Wrong?

The helm chart documentation is out-of-sync , I think it would be better to reference directly the helm [README.md](https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/README.md) directly from master or release branches or some other always-up-to-date source.

**Comment by plumbis** [comment]
Once [c/c #4085](https://github.com/crossplane/crossplane/pull/4085) is merged we can copy/paste the content into the docs.
