### ISSUE TITLE
mixup of XRD and CRD in introduction

### ISSUE THREAD

**Issue by sanzoghenzo** [crossplane/docs#427]
### URL

https://github.com/crossplane/docs/blob/5844fef0e5f60739e1f1044d7c693211ab85684c/content/v1.12/getting-started/introduction.md?plain=1#L370-L437

### What's Wrong?

I'm still new to crossplane and k8s, so forgive me if I'm totallywrong, but it seems to me that, at the end of the Composite Resource Definitions chapter and in the Claims chapter of the introduction, the term "Custom Resource Definition" should be changed to "Composite Resource Definition". 
The same applies to "Custom Resources", it should be "Composite Resources".
I think this is important to not confuse newcomers like me with wrong terminology. For a moment I thought I need to create boz XRD and CRD (2 files) with the same content...

**Comment by plumbis** [comment]
Oh, my apologies, that's super confusing. I've gone ahead and fixed this in #435. 

If you have the time I'd love for you to take a look and make sure it looks correct. 

https://645a4b441ff82a000861abdb--crossplane.netlify.app/v1.12/getting-started/introduction/

**Comment by plumbis** [comment]
You're not missing anything, it was an additional mixup I didn't fix. I fixed it now and added a bit more about comparing Claims to Composite Resources.

Thanks again for looking and bringing this to our attention.
