### ISSUE TITLE
Create a KB article on XRD API versioning

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#478]
### What's Missing?

The [new XRD](https://github.com/crossplane/docs/pull/475) doc talks about API versions and talks briefly about Crossplane's recommendations. 

We should have a KB article specifically about XRD versioning and best practices, including: 
- `v1alpha1` is a test to see what works and doesn't work. 
- Probably need to delete the `v1alpha1` and build the `v1beta1` that shouldn't have breaking changes.
- `v1` is full faith in the API

Optionally, but nice to have, would be an example [conversion webhook](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion) to manage a breaking API change.

**Comment by haarchri** [comment]
@plumbis Is this helpful? Check out the repository at https://github.com/haarchri/xrd-webhook for converting webhooks.

**Comment by plumbis** [comment]
This is discussed (lightly) in the XRD chapter. https://docs.crossplane.io/latest/concepts/composite-resource-definitions/#xrd-versions
