### ISSUE TITLE
Useful kubectl commands

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#492]
### What's Missing?
Not exactly a command reference but some useful aliases and queries to help navigate and administer Crossplane clusters. 

Kind of like the [kubectl cheat sheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/)

**Comment by nabuskey** [comment]
Not exactly aliases / queries but kubectl plugins like https://github.com/ahmetb/kubectl-tree or https://github.com/tohjustin/kube-lineage are very useful to follow owner references.

**Comment by haarchri** [comment]
when using `compositionRevisions` with `Selectors` we often use the following - to check which resources uses which version of the revisions

```
kubectl get composite -o="custom-columns=NAME:.metadata.name,SYNCED:.status.conditions[?(@.type=='Synced')].status,REASON:.status.conditions[?(@.type=='Synced')].reason,REVISION:.spec.compositionRevisionRef.name,POLICY:.spec.compositionUpdatePolicy,MATCHLABEL:.spec.compositionRevisionSelector.matchLabels"



NAME            SYNCED  REASON            REVISION                                            	POLICY     MATCHLABEL
xxx-dev-1wlwk   True    ReconcileSuccess  xtenantaccounts.aws.example.cloud-12d5f8c       	Automatic  map[version:v1.0.0]
yyy-dev-2wlwk   True    ReconcileSuccess  xtenantaccounts.aws.example.cloud-34d5f8c       	Automatic  map[version:v1.0.1]
aaa-dev-3wlwk   True    ReconcileSuccess  xtenantaccounts.aws.example.cloud-56d5f8c      	Automatic  map[version:v1.0.2]
bbb-dev-4wlwk   True    ReconcileSuccess  xtenantaccounts.aws.example.cloud-78d5f8c      	Automatic  map[version:v1.1.0]
ccc-dev-5wlwk   True    ReconcileSuccess  xtenantaccounts.aws.example.cloud-90d5f8c     	Automatic  map[version:v2.0.0]
ddd-dev-6wlwk   True    ReconcileSuccess  xtenantaccounts.aws.example.cloud-01d5f8c       	Automatic  map[version:v2.1.0]
```

**Comment by haarchri** [comment]
for official-providers:

whenever we encounter a failed status in a managed resource with` lifecycle.prevent_destroy`:

` observe failed: cannot run plan: plan failed: Instance cannot be destroyed: Resource google_container_cluster.nodepool has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.`

we can effortlessly facilitate debugging using a small script:

```
#!/bin/bash
set -e

# Get the UID of the nodepool
uidpath=$(kubectl get cluster.container.gcp.upbound.io/nodepool -o jsonpath='{.metadata.uid}')

# Retrieve the pods in the crossplane-system namespace, filter for "provider-gcp",
# extract their names, and then execute a series of commands on each of them.
kubectl get pods -n crossplane-system | grep "provider-gcp" | awk '{print $1}' | xargs -I% kubectl exec -it % -n crossplane-system -- /bin/bash -c \
"cd /tmp/$uidpath/; sed -i 's/\"lifecycle\":{\"prevent_destroy\":true},//g' main.tf.json; terraform init; terraform plan"
```

and we find the following field caused the issue:

![image](https://github.com/crossplane/docs/assets/21083497/e6e5607b-e723-4aba-85a5-416c3677338e)

**Comment by ra0e** [comment]
Maybe an ide: We (the community) should create a repository with the name `awesome-crossplane` where we not just gather all shell-hacks also keep some example and best practice. And fully community driven. Any thoughts?

**Comment by plumbis** [comment]
Thank you for the suggestions everyone. Right now the commands don't have a good home in the docs but if we build out a troubleshooting/admin guide we can revisit the suggestions here.
