### ISSUE TITLE
Install Crossplane offline

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#493]
### What's Missing?

How do you install crossplane in an airgapped environment? Include info about installing providers as well. 

Comment from slack

>You can pull the public images, tag them with your private registry and push them. It should work for both Crossplane and providers (edited)

**Comment by bobh66** [comment]
Also see https://github.com/crossplane/crossplane/issues/4299

**Comment by plumbis** [comment]
https://github.com/crossplane/crossplane/issues/4299#issuecomment-1691379712
