### ISSUE TITLE
update "Import resources automatically" after `Support Granular management policies`

### ISSUE THREAD

**Issue by haarchri** [crossplane/docs#497]
### What's Missing?

after we merging the following PRs we need to update the documentation 

The old
`spec.managmentPolicy: FullControl/ObserveOnly/OrphanOnDelete`
is getting replaced by
`spec.managementPolicies:["*", "Observe", "Create", "Update", "LateInitialize", "Delete"]`

https://github.com/upbound/upjet/pull/224
https://github.com/upbound/provider-aws/pull/785
https://github.com/upbound/provider-gcp/pull/336
https://github.com/upbound/provider-azure/pull/495

**Comment by haarchri** [comment]
I'm contemplating whether it's necessary to clarify whether we should drop the old design document or not...

https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md
vs.
https://github.com/crossplane/crossplane/blob/master/design/one-pager-ignore-changes.md#deletion-policy

**Comment by lsviben** [comment]
> I'm contemplating whether it's necessary to clarify whether we should drop the old design document or not...
> 
> https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md vs. https://github.com/crossplane/crossplane/blob/master/design/one-pager-ignore-changes.md#deletion-policy

Can we use the Status field? ObserveOnly -> Deprecated, IgnoreChanges -> Approved/Implemented/Accepted?

**Comment by plumbis** [comment]
@haarchri are there changes to Crossplane to support these new statuses? Is this something entirely in the scope of providers?
