### ISSUE TITLE
Add Upgrade Process

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#545]
### What's Missing?
The install/upgrade/uninstall section doesn't have upgrade.

Discussion started on what's the "official" upgrade path.
https://github.com/crossplane/crossplane/discussions/4569

**Comment by jbw976** [comment]
For the time being, I think this is a workable set of commands to upgrade Crossplane:

```
helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update
helm upgrade crossplane --namespace crossplane-system crossplane-stable/crossplane
```
