### ISSUE TITLE
[Web Bug] - Example Error in Environment Configs

### ISSUE THREAD

**Issue by youyongsong** [crossplane/docs#580]
In the example of [Patch an individual resource](https://docs.crossplane.io/latest/concepts/environment-configs/#patch-an-individual-resource) section, `spec.resources[0].patches[0].fromFieldPath` value is `status.atProvider.id`.

But it was clearly pointed out in [Patch and Transforms | ToEnvironmentFieldPath](https://docs.crossplane.io/latest/concepts/patch-and-transform/#toenvironmentfieldpath), the `ToEnvironmentFieldPath` patch happens before creating a resource, the `fromFieldPath` can’t read from the `atProvider` or `Status` fields.

URL: https://docs.crossplane.io/latest/concepts/environment-configs/

**Comment by haarchri** [comment]
the default is optional - so in the second loop the patch will evaluated
