### ISSUE TITLE
Remove "Installing and Upgrading? knowledge base entry?

### ISSUE THREAD

**Issue by negz** [crossplane/docs#581]
https://docs.crossplane.io/knowledge-base/install/

These documents cover updating to v0.14 and v1.0. Those releases are 3+ years old - should we remove the documentation?

**Comment by plumbis** [comment]
Yes we should. This is going to be part of a larger effort to clean up the KB coming up in the next few months.

**Comment by plumbis** [comment]
The section was removed. Closing as completed
