### ISSUE TITLE
Document Realtime Compositions alpha feature

### ISSUE THREAD

**Issue by jbw976** [crossplane/docs#588]
### What's Missing?

There is a new alpha feature in Crossplane v1.14 called Realtime Compositions that speeds up the reconciliation of Compositions when they are updated. It can be enabled with `--enable-realtime-compositions`.  

Some explanation of what the feature does and how to enable it will be good for discoverability. It's a fairly low level feature, so we should be aware of the potential audience for it.

The available feature flags section should be updated with this new flag as well, e.g. https://docs.crossplane.io/v1.13/software/install/#feature-flags 

Relevant PRs and issues:

* https://github.com/crossplane/crossplane/pull/4582
* https://github.com/crossplane/crossplane/pull/4637
* https://github.com/crossplane/crossplane/issues/4828

**Comment by sttts** [comment]
Created https://github.com/crossplane/docs/issues/588.
