### ISSUE TITLE
Release Crossplane version v1.14.0 

### ISSUE THREAD

**Issue by turkenh** [crossplane/docs#598]
- [x] Update the `$LATEST_VER` parameter in [netlify_build.sh](https://github.com/crossplane/docs/blob/master/netlify_build.sh#L3)
- [x] Update `params.latest` in [config.yaml](https://github.com/crossplane/docs/blob/master/config.yaml#L48)
- [x] Update `version` in the `_index.md` file of `/content/<new latest>`
- [x] Create a [new release/tag](https://github.com/crossplane/docs/releases/new) named "v<EOL version>-archive" to snapshot EOL'd docs.
- [x] Remove EOL'd docs version from "/content" directory and run `hugo` locally to check for broken links.
- [x] Trigger [Algolia Crawler](https://crawler.algolia.com/) after publishing to reindex results.

**Comment by turkenh** [comment]
Looks like @plumbis is already on it: https://github.com/crossplane/docs/pull/596

**Comment by plumbis** [comment]
Docs published and Algolia reindex completed. Marking as complete.
