### ISSUE TITLE
Make "master" directory use easier

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#600]
When we are about to publish docs the fact there is "master" and a unpublished release creates a commit and syncing problem. 

It's also confusing when navigating the docs since you can't (accidentally) install the master release. 

We should (again) consider getting rid of the master folder.

**Comment by phisco** [comment]
If we removed master today, where should we put docs for new functionalities that will be in 1.15, now that 1.14 is out? I thought master was for that.

**Comment by plumbis** [comment]
Today that's true. The problem is that when we prepare a new release there are a [number of things ](https://github.com/crossplane/docs/blob/master/.github/ISSUE_TEMPLATE/new_release.md) that have to be updated to make the build and publish parts all point to the new $latest version. 

There are two options:
1. We create a new version folder before the release and add new content there along with the required infra changes to make sure it all works in staging. Contributors have to be mindful to contribute to two or three places (master, $old_latest, $new_latest) and/or the right branch.
2. We turn master in to $new_latest as the last step in the release process, change the infra settings and push.

The problem with (2) is that it makes the release unnecessarily risky and stressful. Failure to get some of the things correct either delays docs readiness or causes other issues in the docs, like what redirects, dropdowns and landing pages look like. 

I don't have an answer to the problem yet, but I'm not a fan with what we have today.

**Comment by phisco** [comment]
I feel like you are describing all good reasons to use release branches 😅

**Comment by plumbis** [comment]
The challenge is that our build artifact is a monolith. It doesn't lend itself well to having branches with different shortcodes/layout/templates/structure. 

IMO release branches just shifts the problem around, making the standard build process more complex.

**Comment by plumbis** [comment]
After the 1.15 release I'm not sure there's a great solution that isn't just more process without any benefit. Closing this as "won't fix"
