### ISSUE TITLE
[Web Bug] - Install Crossplane

### ISSUE THREAD

**Issue by jjjjeeffff** [crossplane/docs#605]
Seeing the following when enabling management policies as shown in the docs with `--enable-management-policies`:

```crossplane: error: unknown flag --enable-management-policies```

Installed version 1.14.0 via Helm chart, referencing 1.14.0 docs. Reading [this](https://docs.crossplane.io/latest/concepts/managed-resources/#managementpolicies) it sounds like the flag is no longer required and can be removed from the table on the install page for 1.14.0+.

URL: https://docs.crossplane.io/latest/software/install/

**Comment by plumbis** [comment]
Sorry about the confusion @jjjjeeffff.

The flag `--enable-management-policies` should be applied to a Provider's pod with a [ControllerConfig](https://docs.crossplane.io/v1.14/concepts/providers/#configure-a-provider)

If it's enabled by default in a given provider or not depends on which version of "crossplane-runtime" the Provider uses.

**Comment by plumbis** [comment]
I've fixed the docs in #607 to remove the reference.
