### ISSUE TITLE
v1.15 Features

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#681]
Features needing docs or updates for v1.15:
```[tasklist]
### TODO
- [x] #678
- [x] #680
- [x] https://github.com/crossplane/docs/issues/670
- [x] #682
- [ ] #683
- [ ] #684
- [x] #685
- [ ] #698
- [ ] https://github.com/crossplane/docs/pull/705
```

**Comment by lsviben** [comment]
Please add https://github.com/crossplane/docs/issues/670 as well to the list

**Comment by lsviben** [comment]
This one as well https://github.com/crossplane/docs/issues/682 please! 🙏

**Comment by ezgidemirel** [comment]
Please add https://github.com/crossplane/docs/issues/683 and https://github.com/crossplane/docs/issues/684 to the list.

**Comment by phisco** [comment]
please also https://github.com/crossplane/docs/issues/685

**Comment by plumbis** [comment]
1.15 shipped and the PR for the last issue is currently in review. closing as complete.
