### ISSUE TITLE
Extend render command's doc with new flag

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/docs#683]
### What's Missing?

`--include-full-xr` flag is introduced with this [change](https://github.com/crossplane/crossplane/pull/5248) and needs to be documented.

**Comment by phisco** [comment]
This too https://github.com/crossplane/crossplane/pull/5247 introduced two more flags to the render command, `--extra-resources` and `--include-context`, might be worth adding them all together 😬

**Comment by plumbis** [comment]
PR in #695
