### ISSUE TITLE
[Web Bug] - Configuration Packages

### ISSUE THREAD

**Issue by PierrePIRONIN** [crossplane/docs#689]
The `crossplane xpkg build` option `--output` was renamed to `--package-file`. Documentation needs to be updated accordingly.

URL: https://docs.crossplane.io/latest/concepts/packages/

**Comment by plumbis** [comment]
Good catch and thank you! Sorry for the mixup.

PR #719 was filed with a fix. Looks like we have the right command everywhere else.
