### ISSUE TITLE
[Web Bug] - Tables are unreadable in Dark Mode

### ISSUE THREAD

**Issue by Joro97** [crossplane/docs#690]
The `All Crossplane Customization Options` section of the install docs is almost unreadable in Dark Mode.
Steps to `Reproduce`:

1. Turn on Dark Mode
2. Expand the `All Crossplane Customization Options` section of the docs and see how it looks.

Tested on latest version Brave Browser. 

URL: https://docs.crossplane.io/latest/software/install/

![image](https://github.com/crossplane/docs/assets/41049731/ccc181f5-c5b6-4c65-a8c7-7845a76c9f9d)

**Comment by jbw976** [comment]
I see similar with dark mode in chrome on my mac laptop. Tables on many pages are difficult to read like this, for example: https://docs.crossplane.io/v1.14/cli/command-reference/#global-flags
![Screenshot 2024-02-01 at 8 56 05 AM](https://github.com/crossplane/docs/assets/4313439/1ab5244d-0034-4803-9381-2ca793148db5)

**Comment by jbw976** [comment]
Updated the title to reflect that this is more wide spread than just the install crossplane page @Joro97 🙇‍♂️

**Comment by plumbis** [comment]
I pushed a fix for this in PR #700.

@Joro97 can you take a look and let me know what you think ?

https://deploy-preview-700--crossplane.netlify.app/v1.14/software/install/#installation-options

**Comment by jbw976** [comment]
That looks better to me @plumbis! 🎉 

https://deploy-preview-700--crossplane.netlify.app/v1.14/cli/command-reference/#global-flags

**Comment by Joro97** [comment]
Thanks for the fix and good job!
