### ISSUE TITLE
[Web Bug] - Configuration Packages Does not contain descriptive enough examples

### ISSUE THREAD

**Issue by Joro97** [crossplane/docs#691]
`Install offline` section needs more descriptive examples. I have tried using PVC that mounts properly to the pod, but it cant read/pull the `.xpkg` file no matter what is done. The error from describing the `Configuration` itself is super undescriptive as well. I have tried creating a few `.xpkg` files and putting them in the mounted directory, I have also tried using a `ConfigMap` for the package cache, but the `Configuration` cant find it at all. I havent been able to find a working example on the internet as well. Please consider improving those docs with working E2E examples.  

URL: https://docs.crossplane.io/latest/concepts/packages/

**Comment by Joro97** [comment]
@plumbis could you please take a look when possible or ping someone that could? I could try to provide more descriptive/reproduce-able examples, but basically following the `Install offline` section of the linked docs does not work.

**Comment by plumbis** [comment]
@Joro97 - ack.  I'll try to take a look next week or the week after. We have the 1.15 release coming soon that's the main focus for the team at the moment. After we get the big parts of that done I can come take a look and fix this up for you.

Sorry for the troubles. :(

**Comment by plumbis** [comment]
@Joro97 I spent some time on this and I'm having problems getting crossplane to use the local image in the package cache. I'll keep working on this get the docs updated on the package cache and offline install.

**Comment by Joro97** [comment]
@plumbis awesome, thanks a lot for your work on this!

**Comment by plumbis** [comment]
@Joro97 , working through this it's much more complicated and related to the internal mechanics of the Crossplane package cache than it appears on the surface.

We're still discussing but likely the guidance will be to have users in air gapped environments use a local private registry to pull images from. 

Is this an option for you or is there a specific need to install Crossplane packages in an isolated environment without a local registry?

**Comment by Joro97** [comment]
@plumbis  Sorry, but I dont recall if there was a specific reason for not using local registry or if we have tried following the docs for that and it also didnt work. Also thanks for your help through this.

**Comment by plumbis** [comment]
No problem, I was just curious. I pushed and update to the docs removing the references to the local package cache and instead just recommend using the private registry. 

If that's not an option I can provide you some pointers to try and get it working using the volume mounts for the package cache, but I was never successful.
