### ISSUE TITLE
[Web Bug] - Crossplane CLI

### ISSUE THREAD

**Issue by brovoca** [crossplane/docs#696]
The link under **Manually install the Crossplane CLI** points to the Crossplane controller binary.

>If you don’t want to run shell script you can manually download a binary from the Crossplane releases repository at https://releases.crossplane.io/stable/current/bin

URL: https://docs.crossplane.io/latest/cli/

**Comment by phisco** [comment]
It also states: `The CLI is named crank in the release repository. Download this file.`
If you download `crank` it should be the right file.

**Comment by jbw976** [comment]
Definitely a good point @brovoca! That should get sorted out as well when the Crossplane CLI moves to its own repo: https://github.com/crossplane/crossplane/issues/4850 🙇‍♂️
