### ISSUE TITLE
Document the `--enable-claim-ssa` feature flag

### ISSUE THREAD

**Issue by negz** [crossplane/docs#698]
### What's Missing?

We should document the flag introduced in https://github.com/crossplane/crossplane/pull/5313:

* The new SSA-based claim controller fixes a bunch of bugs (especially when used w/functions), mostly because it implements https://github.com/crossplane/crossplane/issues/4581.
* There's a behavior change in that changes won't be back-propagated from XR spec -> claim spec anymore.

**Comment by plumbis** [comment]
Is this planned to be in 1.15?

**Comment by negz** [comment]
@plumbis It is, yes.
