### ISSUE TITLE
Update all references to master branch for crossplane and crossplane-runtime repositories

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/docs#807]
The https://github.com/crossplane/crossplane and https://github.com/crossplane/crossplane-runtime repositories have switched their primary branch from `master` to `main`.

**Comment by jbw976** [comment]
Was this solved by https://github.com/crossplane/docs/pull/808?

**Comment by jeanduplessis** [comment]
Yes, closing this issue as resolved now.
